### ISSUE TITLE
set up docsify

### ISSUE THREAD

**Issue by nickehsani** [cse110-fa22-group13/cse110-fa22-group13#31]
- Set up the documentation

**Comment by Donttestturing** [comment]
Hey everybody, just as an update. I am encountering some issues with docsify. I might have misunderstood docsify's capabilities

I do have a simple version of JSdocs working though

**Comment by Donttestturing** [comment]
It does not seem to tag content as easily as JSDocs

**Comment by Donttestturing** [comment]
We have Github Actions set up to auto run JSdocs on the .js files in the src folder in the tester app. The github action then deploys that folder to the repo page as documentation.

The repo is here: https://github.com/Donttestturing/testElectronApp

Documentation webpage is here: (Note the time stamps updating with every push)
https://donttestturing.github.io/testElectronApp/
